/** 
 * @Description: 
 * @Author: yaozu.hu
 * @Date: 2021-02-01 11:09:21
 * @Last Modified by: yaozu.hu
 * @Last Modified time: 2021-02-06 16:12:10
 */

export enum ArenaTeamEvent {
    RSP_ARENATEAM_REDPOINT = "RSP_ARENATEAM_REDPOINT",
    RSP_ARENATEAM_TEAMCHANGE = "RSP_ARENATEAM_TEAMCHANGE",
    RSP_ARENATEAM_INVITER = "RSP_ARENATEAM_INVITER",
    RSP_ARENATEAM_INVITER_AGREE = "RSP_ARENATEAM_INVITER_AGREE",
    RSP_ARENATEAM_INVITER_REJECT = "RSP_ARENATEAM_INVITER_REJECT",
    RSP_ARENATEAM_CHANGETIMES_REWARD = "RSP_ARENATEAM_CHANGETIMES_REWARD",
    RSP_ARENATEAM_RANK_REWARD = "RSP_ARENATEAM_RANK_REWARD",
}
