/**
  * @Description: 抽奖事件id
  * @Author: weiliang.huang
  * @Date: 2019-05-27 17:23:53
 * @Last Modified by: yaozu.hu
 * @Last Modified time: 2021-06-04 14:13:17
*/

export enum LotteryEventId {
  REQ_LUCKY_DRAW = "REQ_LUCKY_DRAW",   //请求抽奖

  RSP_LUCKY_COMPOSE = "RSP_LUCKY_COMPOSE", // 合卡返回
  RSP_LUCKY_DRAW = "RSP_LUCKY_DRAW",//抽卡返回

  SELECT_LOTTERY_ITEM = "SELECT_LOTTERY_ITEM",//选中指定的item
  SELECT_COMPOSE_SLOT = "SELECT_COMPOSE_SLOT",//选中指定合卡的slot

  ACTIVE_COMPOSE = "ACTIVE_COMPOSE", //解锁合成公式
  UPDATE_COMPOSE_STATUS = "UPDATE_COMPOSE_STATUS", //奖励领取status更新
  CHILD_CLICK = "CHILD_CLICK", //点击合成公式的子英雄
  SHOW_NEXT_ITEM = "SHOW_NEXT_ITEM", //显示下一个抽卡奖励
  SHOW_ITEM_END = "SHOW_ITEM_END", //抽奖展示结束

  COMPOSE_RED_POINT_FLAG_CHANGE = "COMPOSE_RED_POINT_FLAG_CHANGE", //英雄碎片合成界面 红点开关改变

  UPDATE_LOTTERY_CREDIT_CHANGE = "UPDATE_LOTTERY_CREDIT_CHANGE",//抽奖积分改变

  UPDATE_LOTTERY_ITEM_CHECK = "UPDATE_LOTTERY_ITEM_CHECK", // 抽奖道具新增情况已查看 红点

  GENE_POOL_SELECT = "GENE_POOL_SELECT", //基因卡池选择
  GENE_LOTTERY_REQ = "GENE_LOTTERY_REQ", //基因抽奖
  HERO_ALL_RESET_SELECT = "HERO_ALL_RESET_SELECT", //批量重置选择

  HERO_TRANS_MATERIAL_SELECT = "HERO_TRANS_MATERIAL_SELECT", //英雄置换材料选择
  HERO_TRANS_MATERIAL_PRE_SELECT = "HERO_TRANS_MATERIAL_PRE_SELECT", //英雄置换材料预选择

  HERO_RESET_TYPE_CHANGE = "HERO_RESET_TYPE_CHANGE",//拆解界面类型变化

}