/**
  * @Description: 角色事件枚举
  * @Author: weiliang.huang
  * @Date: 2019-04-10 10:10:06
 * @Last Modified by: luoyong
 * @Last Modified time: 2021-09-07 17:45:19
*/

export enum RoleEventId {
  RSP_STRENGTH_EQUIP = "RSP_STRENGTH_EQUIP",  // 强化装备回调
  // RSP_EQUIP_FM = "RSP_EQUIP_FM", // 装备附魔返回
  RSP_EQUIP_SAVE_FM = "RSP_EQUIP_SAVE_FM", // 保存附魔返回
  RSP_EQUIP_MERGE = "RSP_EQUIP_MERGE",//装备融合返回

  UPDATE_EQUIP_LIST = "UPDATE_EQUIP_LIST", // 更新所有装备
  UPDATE_ONE_EQUIP = "UPDATE_ONE_EQUIP",   // 更新单个装备
  UPDATE_ONE_EQUIP_TP_TIP = "UPDATE_ONE_EQUIP_TP_TIP",   // 更新单个装备突破的标签
  UPDATE_SELECT_EQUIP = "UPDATE_SELECT_EQUIP",   // 更新选择装备
  RSP_EQUIP_OFF = "RSP_EQUIP_OFF",   // 卸下单个装备
  REMOVE_ONE_EQUIP = "REMOVE_ONE_EQUIP",   // 删除单个装备
  UPDATE_ROLE_EQUIP_PANEL = "UPDATE_ROLE_EQUIP_PANEL", // 更新英雄装备界面的选择项
  UPDATE_CURR_EQUIP_INFO = "UPDATE_CURR_EQUIP_INFO",  // 更新当前选中的装备

  UPDATE_HERO_LIST = "UPDATE_HERO_LIST", // 更新所有英雄
  UPDATE_ONE_HERO = "UPDATE_ONE_HERO", // 更新单个英雄
  UPDATE_HERO_ATTR = "UPDATE_HERO_ATTR", //更新英雄属性
  UPDATE_HERO_POWER = "UPDATE_HERO_POWER", //更新英雄战斗力
  REMOVE_ONE_HERO = "REMOVE_ONE_HEROP",   // 删除单个英雄
  UPDATE_CURR_HERO_INFO = "UPDATE_CURR_HERO_INFO",  // 更新当前选中的英雄
  REMOVE_HERO_FIGHT_INFO = "REMOVE_HERO_FIGHT_INFO",  // 删除英雄战斗属性

  REQ_CHANGE_NAME = "REQ_CHANGE_NAME", // 请求改名

  SHOW_EQUIP_SELECT = "SHOW_EQUIP_SELECT", // 显隐装备选择界面

  SHOW_STRENGTH_FADE = "SHOW_STRENGTH_FADE", // 装备-强化材料选择界面,点击空白材料框闪烁装备格子

  ROLE_ATT_UPDATE = "ROLE_ATT_UPDATE", // 角色属性更新

  UPDATE_EQUIP_SELECT_CLOSE = "UPDATE_EQUIP_SELECT_CLOSE",  // 更新装备选择面板上的标签切换

  SHOW_HERO_UP_EFFECT = "SHOW_HERO_UP_EFFECT",//英雄升级
  SHOW_JOB_RESULT_EFFECT = "SHOW_JOB_RESULT_EFFECT",//职业进阶结果特效
  SHOW_EQUIP_STRENTH_MERGE_SKILL = "SHOW_EQUIP_STRENTH_MERGE_SKILL",//融合装备强化后技能再次展示

  SHOW_UPPANEL_EFFECT = "SHOW_UPPANEL_EFFECT",//英雄界面---上部分闪光效果
  SHOW_UPPANEL_EFFECT_END = "SHOW_UPPANEL_EFFECT_END",//英雄界面---上部分闪光效果完成

  SHOW_UPHERO_INFO = "SHOW_UPHERO_INFO",//上阵英雄修改

  RUNE_OFF = "RUNE_OFF", //符文卸下
  RUNE_ON = "RUNE_ON", //穿戴符文
  RUNE_REMOVE = "RUNE_REMOVE", //符文删除
  RUNE_ADD = "RUNE_ADD", //符文新增

  COMMENT_MARK_PUT_IN = "COMMENT_MARK_PUT_IN",//标签快速写入
  COMMENT_REFRESH_DATA = 'COMMENT_REFRESH_DATA',//刷新评论信息


  COSTUME_ADD = "COSTUME_ADD",//神装新增
  COSTUME_REMOVE = "COSTUME_REMOVE",//神装删除

  GUARDIAN_REMOVE = "GUARDIAN_REMOVE",//守护者删除
  GUARDIAN_ADD = "GUARDIAN_ADD",//守护者增加

  GUARDIANEQUIP_UPDATE = "GUARDIANEQUIP_UPDATE",//背包守护者装备更新
  GUARDIAN_INHERO_EQUIP_UPDATE = "GUARDIAN_INHERO_EQUIP_UPDATE",//守护者身上的装备更新

  GUARDIAN_BACK_SELECT = "GUARDIAN_BACK_SELECT", //守护者回退 守护者选择

  GENE_CONNECT_HERO_SELECT = "GENE_CONNECT_HERO_SELECT", //基因链接 链接英雄选择

  MYSTIC_SKILL_MATERIALS_SELECT = "MYSTIC_SKILL_MATERIALS_SELECT", //神秘者 技能材料选择

  UPDATE_UNIQUEEQUIP_LIST = 'UPDATE_UNIQUEEQUIP_LIST', //专属装备列表更新
  UPDATE_ONE_UNIQUEEQUIP = 'UPDATE_ONE_UNIQUEEQUIP', //更新某一专属装备
  REMOVE_ONE_UNIQUEEQUIP = 'REMOVE_ONE_UNIQUEEQUIP', //删除某一专属装备
  UPDATE_HERO_UNIQUE_EQUIP = "UPDATE_HERO_UNIQUE_EQUIP",//更新英雄专属装备
}