export enum FootHoldEventId {

    UPDATE_FOOTHOLD_POINT_BROADCAST = "UPDATE_FOOTHOLD_POINT_BROADCAST", //地图信息点更新 

    UPDATE_FOOTHOLD_DROP_REWARD = "UPDATE_FOOTHOLD_DROP_REWARD", //据点战结算是否有奖励领取

    UPDATE_FOOTHOLD_SEND_REWARD = "UPDATE_FOOTHOLD_SEND_REWARD", //据点战会长是否有奖励发放

    REFRESH_FOOTHOLD_SEND_REWARD_STATE = "REFRESH_FOOTHOLD_SEND_REWARD_STATE", //刷新可发奖励按钮状态

    REFRESH_FOOTHOLD_SEND_LIST = "REFRESH_FOOTHOLD_SEND_LIST",//刷新发送成员列表

    REFRESH_FHPOINT_COLOR_STATE = "REFRESH_FHPOINT_COLOR_STATE" //刷新据点颜色状态
}