/** 
  * @Author: jiangping  
  * @Description: 
  * @Date: 2021-05-19 14:39:01 
  */
export enum PiecesEventId {
  PIECES_TALENT_CLICK_TO_ACTIVE = "PIECES_TALENT_CLICK_TO_ACTIVE", //请求激活天赋

  PIECES_HAND_CARD_UPDATE = "PIECES_HAND_CARD_UPDATE", //手牌更新

  PIECES_PVP_HERO_UP_STAR = "PIECES_PVP_HERO_UP_STAR", //PVP 英雄升星

  PIECES_PVP_REMOVE_HERO = "PIECES_PVP_REMOVE_HERO", //PVP 我方英雄删除

  PIECES_PVP_HERO_ON_BATTLE = "PIECES_PVP_HERO_ON_BATTLE", //pvp 我发英雄上下阵

  PIECES_PVP_SHOW_HERO_SELL_ICON = "PIECES_PVP_SHOW_HERO_SELL_ICON", //显示英雄售出图标
  PIECES_PVP_HIDE_HERO_SELL_ICON = "PIECES_PVP_HIDE_HERO_SELL_ICON",  //隐藏英雄售出图标
  PIECES_PVP_ENEMY_DEPLOY_OVER = "PIECES_PVP_ENEMY_DEPLOY_OVER", //敌方布局完毕

  PIECES_PVP_CAREER_CHANGE = "PIECES_PVP_CAREER_CHANGE", //英雄转换路线
}

