/** 
  * @Description: 任务事件id
  * @Author: weiliang.huang  
  * @Date: 2019-05-23 18:03:11 
 * @Last Modified by: jiangping
 * @Last Modified time: 2020-10-13 09:51:31
*/

export enum TaskEventId {
  UPDATE_ONE_TASK = "UPDATE_ONE_TASK", // 更新单个任务

  UPDATE_TASK_AWARD_STATE = "UPDATE_TASK_AWARD_STATE", // 更新任务领奖状态
  UPDATE_ONLINE_INFO = "UPDATE_ONLINE_INFO", //更新在线奖励信息

  UPDATE_TASK_GROW_INFO = "UPDATE_TASK_GROW_INFO", //更新成长任务信息

  UPDATE_TASK_WEAPON_INFO = "UPDATE_TASK_WEAPON_INFO", //更新神器任务信息

  UPDATE_CLEARANCE_GROW_ONLINE_RED = "UPDATE_CLEARANCE_GROW_ONLINE_RED", //更新通关奖励、成长任务、在线奖励 红点消息

  UPDATE_TASK_SEVEN_DAYS_SCORE_AWARD_STATE = "UPDATE_TASK_SEVEN_DAYS_SCORE_AWARD_STATE",//开服7天活动

  UPDATE_TAVERN_TASK = "UPDATE_TAVERN_TASK", // 酒馆任务列表更新

  TAVERN_HERO_CHOOSE_PANEL_CLICK = "TAVERN_HERO_CHOOSE_PANEL_CLICK", // 酒馆任务英雄选择面板选择了英雄   
  TAVERN_HERO_SELECTED = "TAVERN_HERO_SELECTED", // 酒馆任务英雄上阵
  TAVERN_HERO_UN_SELECTED = "TAVERN_HERO_UN_SELECTED", // 酒馆任务英雄下阵
  TAVERN_TASK_COUNT_DOWN_OUT = "AVERN_TASK_COUNT_DOWN_OUT", //酒馆任务倒计时结束
  TAVERN_LV_UP = "AVERN_LV_UP", //酒馆升级
  TAVERN_TASK_START = "TAVERN_TASK_START", //酒馆任务开始

  SEVENDAYS_STORE_SELL_OUT = "SEVENDAYS_STORE_SELL_OUT",//七日狂欢商店物品售罄

  UPDATE_GUILD_TASK = "UPDATE_GUILD_TASK",//更新公会任务
  UPDATE_GUILD_TASK_REWARD = "UPDATE_GUILD_TASK_REWARD",//更新公会任务奖励
}